name: ALZ Identity Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        default: NonProduction
        type: choice
        options:
          - NonProduction
      action:
        description: Terraform Action
        required: true
        default: plan
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  deploy-identity:
    uses: ./.github/workflows/alz-run-all.yml
    with:
      subscription_name: identity
      terraform_action: ${{ github.event.inputs.action }}
      environment: ${{ github.event.inputs.environment }}
      terraform_root: alz-platform/pattern1/identity_dev
      tfvars_file: alz-platform-vars/pattern1/identity.tfvars
    secrets: inherit
