name: ALZ Security Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        default: NonProduction
        type: choice
        options:
          - NonProduction
      action:
        description: Terraform Action
        required: true
        default: plan
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  deploy-security:
    uses: ./.github/workflows/alz-run-all.yml
    with:
      subscription_name: security
      terraform_action: ${{ github.event.inputs.action }}
      environment: ${{ github.event.inputs.environment }}
      terraform_root: alz-platform/pattern1/security
      tfvars_file: alz-platform-vars/pattern1/security.tfvars
    secrets: inherit
