name: ALZ Connectivity CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "alz-platform/pattern1/connectivity/**"
      - ".github/workflows/alz-ci-connectivity.yml"
      - ".github/workflows/alz-ci-template.yml"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/alz-ci-template.yml
    with:
      stack_name: connectivity
      stack_path: ./alz-platform/pattern1/connectivity
      environment_name: connectivity
    secrets: inherit
