name: ALZ Identity CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "alz-platform/pattern1/identity_dev/**"
      - ".github/workflows/alz-ci-identity.yml"
      - ".github/workflows/alz-ci-template.yml"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/alz-ci-template.yml
    with:
      stack_name: identity
      stack_path: ./alz-platform/pattern1/identity_dev
      environment_name: identity
    secrets: inherit
